Integrated Simultaneous Equation solver in CLI
aerospaceresearch/VisMa pull request #187
Opened 2019-05-01 19:39 UTC by mayankDhiman

**_Changelog:_**
+ integrated simultaneous equation solver in CLI.
+ made simultaneous equation accept arguments as tokens, as like in other modules.
+ made simultaneous equation solver solve for other variables except `x`, `y and `z`.
+ added test cases showing above behaviour. 
+ moved the module which generates the final result string in CLI to `io/parser` with other i/o modules.

**_Test cases: _**
[Here](https://pastebin.com/QnYs8Qpe) are the test cases showing the result produced by simultaneous equation solver in CLI.

_some errors regarding displaying results in CLI, might be there, which I will be solved with next patches_

2019-05-05 17:15 UTC, 8hantanu requested changes
You can add a default 'solve for all variable' option when the variable is not specified in your next patch.

`solve(1000x + 2y + 3z = 4; 5x + 6y + 7z = 8; 9x + 10y + 11z = 12)` must solve for x, y and z.

2019-05-05 17:15 UTC, 8hantanu commented on visma/solvers/simulEqn.py
> +    matD {visma.matrix.structure.Matrix.SquareMat} -- Matrix Token
```suggestion
        matD {visma.matrix.structure.Matrix.SquareMat} -- Matrix Token
```
Same in `simulSolver` docstring.

2019-05-05 17:15 UTC, 8hantanu commented on visma/io/parser.py
> +    finalSteps = ''
:+1: for adding step comments

2019-05-06 07:11 UTC, mayankDhiman commented on visma/io/parser.py
> +    finalSteps = ''
Thanks :)

2019-05-06 07:13 UTC, 8hantanu approved these changes

2019-05-06 12:25 UTC, merged